[project]
name = "klaviyo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.12.4",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "typer>=0.16.0",
    "uv>=0.8.9",
]
